services:
  app:
    container_name: api
    build: ./epytodo
    ports:
      - "5000:5000"
    environment:
      MYSQL_DATABASE: epytodo
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
    networks:
      - epytodo-network
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: database
    image: mariadb:10.11
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: epytodo
      MYSQL_USER: epytodo_user
      MYSQL_PASSWORD: epytodo_password
    networks:
      - epytodo-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./epytodo/epytodo.sql:/docker-entrypoint-initdb.d/epytodo.sql
    restart: on-failure
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql-data:

networks:
  epytodo-network: